version: '3'
services: 
    bodysoft-gateway-api:
        container_name: bodysoft-gateway-api
        
        build: .
        environment: 
            PORT: '3800'
            CHAT_HOST: 'http://host.docker.internal:4500'
            PROFILE_HOST: 'http://host.docker.internal:8000'
            AUTHENTICATION_HOST: 'http://host.docker.internal:4002'
            ROUTINE_HOST: 'http://host.docker.internal:8443/routine-ms'
            SESSION_HOST: 'http://host.docker.internal:4001'
        ports: 
            - '3800:3800'